platform :ios, '8.0'
inhibit_all_warnings!
use_frameworks!

target 'MelbourneTestProject' do
    
    pod 'ReSwift', '~> 4.0.1'
    pod 'Alamofire', '~> 4.7'
    pod 'Kingfisher', '~> 4.7'

end

target 'MelbourneTestProjectCore' do
    
    pod 'ReSwift', '~> 4.0.1'
    pod 'ObjectMapper', '~> 3.1'
    
end
