platform :ios, '8.0'
inhibit_all_warnings!
use_frameworks!

pod 'Kingfisher', '~> 4.7'
pod 'ReSwift', '~> 4.0.1'
pod 'Alamofire', '~> 4.7'

target 'MelbourneTestProject' do
    
    

end

target 'MelbourneTestProjectCore' do

    pod 'ObjectMapper', '~> 3.1'
    
end
